apiVersion: v1
kind: Pod
metadata:
 name: node-app
 labels:
    app: node-app
    owner: vibhas
    type: backend
spec:
 imagePullSecrets:
   - name: docker-hub-cred 
 containers:
   - name: node-api
     image: dockerusername/k8-node-app:v2
  
